### ISSUE TITLE
Update the Frontend

### ISSUE THREAD

**Issue by deeheber** [deeheber/text-to-speech-converter#36]
- [x] Update all dependencies
- [x] Use newer React conventions like Hooks

**Comment by deeheber** [comment]
Potential issue...no codebuild images officially support Node 16: https://docs.aws.amazon.com/codebuild/latest/userguide/runtime-versions.html.

**Comment by deeheber** [comment]
Ah nevermind looks like there's an override:

```
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - n 16
```
